### ISSUE TITLE
Update/Revise Project Documentation

### ISSUE THREAD

**Issue by lazaridiscom** [GridPlus/cryptobridge-contracts#12]
## Suggested Steps (Prioritized)

- [ ] Provide concise installation steps for (starting with "Prerequisites node.js" etc.), ideal a cli-sequence
- [ ] Provide the additional steps for contributing(!) developers
- [ ] Provide installation remarks re Windows
- [ ] low priority: reduce size of readme.

## Notes

This came up during setup for work on #11. There were missing dependencies and finally problems with installation of termios on windows.

This documentation should be provided by the project, as its beyond the scope of issue #11 

(I will at this point retry the setup using this time an Ubuntu Subsystem on Win10. )

**Comment by lazaridiscom** [comment]
Setup via ubuntu bash was more straightforward, any idea about the cause for this (web lookup does not show it elsewhere). This is possibly related to WSL. Just need to know if you experienced this on your side.

```shell
lazaridiscom@dell-i5-win:/mnt/p/sand/cryptobridge/contract-ubuntu$ npm run parity 7545 8545

> trustless-relay@1.0.0 parity /mnt/p/sand/cryptobridge/contract-ubuntu
> node parity/boot.js "7545" "8545"

/mnt/p/sand/cryptobridge/contract-ubuntu/node_modules/termios/lib/termios.js:34
        return termios.setattr(fd, 0, modes);
                       ^

Error: Invalid argument
    at Object.module.exports.setattr (/mnt/p/sand/cryptobridge/contract-ubuntu/node_modules/termios/lib/termios.js:34:17)
    at Object.module.exports.spawn (/mnt/p/sand/cryptobridge/contract-ubuntu/node_modules/child_pty/lib/child_pty.js:75:10)
    at Spectcl.spawn (/mnt/p/sand/cryptobridge/contract-ubuntu/node_modules/spectcl/lib/spectcl.js:185:26)
    at jsonfile.writeFile (/mnt/p/sand/cryptobridge/contract-ubuntu/parity/boot.js:64:15)
    at /mnt/p/sand/cryptobridge/contract-ubuntu/node_modules/graceful-fs/graceful-fs.js:99:16
    at /mnt/p/sand/cryptobridge/contract-ubuntu/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! trustless-relay@1.0.0 parity: `node parity/boot.js "7545" "8545"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the trustless-relay@1.0.0 parity script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by lazaridiscom** [comment]
moved to #20
