### ISSUE TITLE
Provide Windows Support

### ISSUE THREAD

**Issue by lazaridiscom** [GridPlus/cryptobridge-contracts#13]
(related: #11)

## Problem

The `parity/boot.js` which launches the 2 parity test-instances use npm modules which introduces problems.

Installation on a Windows 10 machine brings up several problems, even if the Bash Shell is used (Windows Linux Subsystem, with Ubuntu 16.04).

The installation on a standard Windows 10 Home machine should be enabled and simplified.

This would possibly mean to either solve existent problems (workarounds or fixes), or (prefered) to  replace the incompatible modules which seem to have low usage & maintenance.

Modules:

* https://www.npmjs.com/package/spectcl
* https://github.com/Gottox/child_pty/issues/20
* https://github.com/Gottox/node-termios

Usage Statistics:

* https://www.npmjs.com/package/spectcl < 200 downloads
* https://www.npmjs.com/package/child_pty - <400 downloads
* https://www.npmjs.com/package/termios - < 400 dowlnloads

in comparison (picked quickly a pupolar module)

* https://www.npmjs.com/package/node-pty > 20k downloads
* https://www.npmjs.com/package/co-child-process > 120k (120.000) downloads
* https://www.npmjs.com/package/child-process-promise

### Overview of steps

- [x] research and select new module
- [x] rewrite code boot.js
- [ ] rename `truffle.js` to e.g. `test-client.js` (name-clash on windows)
- [ ] verify installation on a blank Win10 Home natively
- [ ] update documentation (related: #12)

### Alternative

* provide dockerimage, like e.g: https://github.com/erkmos/parity-testrpc

### Further Info

* https://github.com/paritytech/parity/wiki/Demo-PoA-tutorial#2-setting-up-the-two-nodes

**Comment by lazaridiscom** [comment]
After going into the code, I realized that "spectcl" seems to be replaceable easily.

**Comment by lazaridiscom** [comment]
UPDATE: with eb32005 (remove dependency to spectcl)

Setup via ubuntu bash was more straightforward, any idea about the cause for this (web lookup does not show it elsewhere). This is possibly related to WSL. Just need to know if you experienced this on your side.

```shell
lazaridiscom@dell-i5-win:/mnt/p/sand/cryptobridge/contract-ubuntu$ npm run parity 7545 8545

> trustless-relay@1.0.0 parity /mnt/p/sand/cryptobridge/contract-ubuntu
> node parity/boot.js "7545" "8545"

/mnt/p/sand/cryptobridge/contract-ubuntu/node_modules/termios/lib/termios.js:34
        return termios.setattr(fd, 0, modes);
                       ^

Error: Invalid argument
    at Object.module.exports.setattr (/mnt/p/sand/cryptobridge/contract-ubuntu/node_modules/termios/lib/termios.js:34:17)
    at Object.module.exports.spawn (/mnt/p/sand/cryptobridge/contract-ubuntu/node_modules/child_pty/lib/child_pty.js:75:10)
    at Spectcl.spawn (/mnt/p/sand/cryptobridge/contract-ubuntu/node_modules/spectcl/lib/spectcl.js:185:26)
    at jsonfile.writeFile (/mnt/p/sand/cryptobridge/contract-ubuntu/parity/boot.js:64:15)
    at /mnt/p/sand/cryptobridge/contract-ubuntu/node_modules/graceful-fs/graceful-fs.js:99:16
    at /mnt/p/sand/cryptobridge/contract-ubuntu/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! trustless-relay@1.0.0 parity: `node parity/boot.js "7545" "8545"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the trustless-relay@1.0.0 parity script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by lazaridiscom** [comment]
## Suggested Workaround

### Windows 10 Home

Upgrade to Windows 10 Pro, which allows for latest Docker, which uses the native virtualization technology.

### Windows 10 Pro

Use Docker

**Comment by lazaridiscom** [comment]
moved to #20
